### ISSUE TITLE
Example not working with older version of Docker

### ISSUE THREAD

**Issue by kevpak** [ca-api-gateway-examples/gateway-metrics-grafana-example#6]
When running `docker-compose -f ./docker-compose.yml` using Docker 17.06, the following error is seen:

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0", "3.1", "3.2") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**Workaround:**
Update the compose file format version to the version that is compatible with the Docker version you are running.
This can be done by opening the docker-compose.yml file and updating value of the `version` or omit the `version` key entirely.

**Comment by kevpak** [comment]
If you encounter the following error in "gateway-metrics-grafana-example" container during startup, then update Docker Compose to the latest version that is compatible with your Docker.

> 2018-12-04T17:03:56.316+0000 WARNING 1      com.l7tech.server.boot.GatewayMain: Error starting server : Lifecycle error: No license loaded. Exiting.
> com.l7tech.server.LifecycleException: Lifecycle error: No license loaded. Exiting.
> 	at com.l7tech.server.BootProcess.start(Unknown Source)
> 	at com.l7tech.server.boot.GatewayBoot.f(Unknown Source)
> 	at com.l7tech.server.boot.GatewayBoot.start(Unknown Source)
> 	at com.l7tech.server.boot.GatewayBoot.runUntilShutdown(Unknown Source)
> 	at com.l7tech.server.boot.GatewayMain.main(Unknown Source)

**Workaround:**
If this still does not work, load the Gateway license file using `volumes` map instead of `secrets`.
This can be done by opening the `docker-compose.yml` file and replacing

```
secrets:
  - source: license
    target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
```

with 
```
volumes:
  - ./docker/license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
```
